
test:
	NODE_ENV=testing \
		node_modules/.bin/babel-node --harmony \
		node_modules/.bin/gulp test

test-watch:
	NODE_ENV=testing \
		node_modules/.bin/babel-node --harmony \
		node_modules/.bin/gulp test-watch

travis:
	NODE_ENV=testing \
		node_modules/.bin/babel-node --harmony \
		node_modules/.bin/gulp travis

.PHONY: test
